version: '3.1'

services:

  # Spin a Postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--lc-collate C --lc-ctype C --encoding UTF8"
    command: -c fsync=off

  # Spin a Synapse
  synapse:
    build: .
    depends_on:
      - postgres
    environment:
      SYNAPSE_POSTGRES_HOST: postgres
      SYNAPSE_POSTGRES_USER: postgres
      SYNAPSE_POSTGRES_PASSWORD: postgres
    working_dir: /data
